version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - SESSION_MAXAGE=${SESSION_MAXAGE}
      # - STALE_WHILE_REVALIDATE=${STALE_WHILE_REVALIDATE}
      - SAMPLER_RATIO=${SAMPLER_RATIO}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BUCKET_NAME=${BUCKET_NAME}
      - URL_EXPIRATION_TIME=${URL_EXPIRATION_TIME}
      - BUCKET_CORS_EXPIRATION_TIME=${BUCKET_CORS_EXPIRATION_TIME}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}